# a mongo db database with sharding enabled and a replica set
version: '3.2'

# mongo db composition
# 1 router
# 3 shards with 1 shard replicated 2 times one on each db instance
# 2 config servers (replica)

services:
  # router
  router:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBRouter
        args:
          - MONGO_ROUTER_PORT = 27017
          - MONGO_CONFIG_SERVERS = config1:27022,config2:27023
          - MONGO_ROUTER_REPLICA_SET_NAME = router
    ports:
      - 27017:27017
    networks:
      - mongo

  # config servers
  config1:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBConfigServer
        args:
          - MONGO_CONFIG_SERVER_PORT = 27022
          - MONGO_CONFIG_SERVER_REPLICA_SET_NAME = config
    ports:
      - 27022:27022
    networks:
      - mongo
  config2:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBConfigServer
        args:
          - MONGO_CONFIG_SERVER_PORT = 27023
          - MONGO_CONFIG_SERVER_REPLICA_SET_NAME = config
    ports:
      - 27023:27023
    networks:
      - mongo

  # shards
  shard1:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBShardServer
        args:
          - MONGO_SHARD_SERVER_PORT = 27018
          - MONGO_SHARD_SERVER_REPLICA_SET_NAME = shard1
    ports:
      - 27018:27018
    networks:
      - mongo
  shard2:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBShardServer
        args:
          - MONGO_SHARD_SERVER_PORT = 27019
          - MONGO_SHARD_SERVER_REPLICA_SET_NAME = shard2
    ports:
      - 27019:27019
    networks:
      - mongo
  shard3:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBShardServer
        args:
          - MONGO_SHARD_SERVER_PORT = 27020
          - MONGO_SHARD_SERVER_REPLICA_SET_NAME = shard3
    ports:
      - 27020:27020
    networks:
      - mongo
  shard4:
    image:
      build:
        context: ./images
        dockerfile: images/mongoDBShardServer
        args:
          - MONGO_SHARD_SERVER_PORT = 27021
          - MONGO_SHARD_SERVER_REPLICA_SET_NAME = shard3
    ports:
      - 27021:27021
    networks:
      - mongo

networks:
  mongo:
    driver: bridge